### PR TITLE
Moving to futures

### PR DESCRIPTION
**Pull request by fruch**
* simplifiy the implemention (no need of quoue)
* add dependecy for older python versions (below 3.2)
* now pass excpetions happing in the thread back to the caller

### CODE REVIEW

**Comment by lord63** [comment]
> now pass excpetions happing in the thread back to the caller

Ah, it seems that the current implementation will have a infinate spin when exception happens. Did you mean that with your patch, it will stop then?

another question is why add an `end` param, could you give me an example to show the original purpose?

You also mentioned the pickling problem, can you show a case with some code?

**Comment by fruch** [comment]
In cases were you want to control the end, for example I have multiple spinners one after another, and I want them to clear the line once it done, and not go to the next line.

For example using vt100 to clear the current line, "\33[2K\r"

**Comment by fruch** [comment]
And yes, exceptions should stop the spinner, since the future won't be in running state anymore. Also it would rise the expectations when future.result() is being called.

**Comment by fruch** [comment]
As for the pickaling, since you initially used subprocess, all your parameters to the function needs to pickaleable, cause they need to be passed to a different process, not all objects are easily pickled (I.e. objects that are partly implemented in C, or object that hold open connection of opened files)

**Comment by fruch** [comment]
@lord63 cool

**Comment by fruch** [comment]
Can you ping, when you'll upload a version with that in pypi ?

**Comment by lord63** [comment]
@fruch Sure! Thanks for your contribution 👍 , I'll release a new version in next two days. I'll ping you back :)

**Comment by fruch** [comment]
You are welcome, I do love decorators, and this one is a fine example of how useful it can be.

You might want to changes the things I've done to your setup.py, and move to environment markers, which should be better suited for this use case.

**Comment by lord63** [comment]
@fruch @xoviat Just released v1.1.0~

**Pull request merged**
